export default [
  {
    key:"1",
    title: 'Burger Anything Takes More Coura',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/NDPBK-d-03M/840x840',
    price: 180,
    horizontal: true,
    favorite: true,
  },
  {
    key:"2",
    title: 'Burger the cheapest deals on our range',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/sc5sTPMrVfk/840x840',
    price: 220,
    horizontal: true,
    favorite: false,
  },
  {
    key:"3",
    title: 'Burger Tango Terry Jersey',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/X92WLoaQ1_o/840x840',
    price: 40,
    horizontal: true,
    favorite: true,
  },
  {
    key:"4",
    title: 'Burger (IoT) is Here to Stay',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/ruwO7jEKNbs/840x840',
    price: 188,
    horizontal: true,
    favorite: true,
  },
  {
    key:"5",
    title: 'Salmon - A Drop of Happiness in a Cup',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/t05q7TZObzc/840x840',
    price: 180,
    horizontal: true,
    favorite: false,
  },
  {
    key:"6",
    title: 'Beer - A Happiness',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/o-EmieeOtrs/840x840',
    price: 190,
    horizontal: true,
    favorite: true,
  },
  {
    key:"7",
    title: 'Beer - API ',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/jNkdYswZ61o/840x840',
    price: 320,
    horizontal: true,
    favorite: false,
  },
  {
    key:"8",
    title: 'Beer Waesteiner',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/LwQEYcsgOMA/840x840',
    price: 240,
    horizontal: true,
    favorite: false,
  },
  {
    key:"9",
    title: 'Beer - Normal ',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/Jk4Q1pFJI2s/840x840',
    price: 280,
    horizontal: true,
    favorite: true,
  },
  {
    key:"10",
    title: 'Beer Leffe',
    detail: "The flavor of your food is what most customers focus on when they are deciding what to eat. and a good menu description could even convince a hesitant customer to try something new",
    image: 'https://source.unsplash.com/nRkp7M39UhA/840x840',
    price: 210,
    horizontal: true,
    favorite: false,
  }
];
