const { REACT_NATIVE_APP_URL_API, REACT_NATIVE_APP_DELAY_SEARCH } = process.env;

export const DELAY_SEARCH = REACT_NATIVE_APP_DELAY_SEARCH;

// const { REACT_NATIVE_APP_AUTH_API } = "http://wangdek.am2bmarketing.co.th/api/v1"
const REACT_NATIVE_APP_API = "http://10.0.1.37:8080/api/v1";

export const API_URL = {
  //AUTHENTICATE
  REGISTER_API: REACT_NATIVE_APP_API + "/register",
  LOGIN_API: REACT_NATIVE_APP_API + "/login",
  USER_INFO_API: REACT_NATIVE_APP_API + "/user",
  EDIT_USER_PROFILE_API: REACT_NATIVE_APP_API + "/user",
  CHANGE_PASSWORD_API: REACT_NATIVE_APP_API + "/user/change_pass",
  PROVINCE_API: REACT_NATIVE_APP_API + "/provinces",
  DISTRICT_API: REACT_NATIVE_APP_API + "/districts",
  SUB_DISTRICT_API: REACT_NATIVE_APP_API + "/sub_districts",

  //API PAGE
  FALSH_SALE_VIEW_API: REACT_NATIVE_APP_API + "/flashsales",
  COUPON_LIST_TR_API: REACT_NATIVE_APP_API + "/coupon/list",
  FAVORITE_VIEW_LIST_API: REACT_NATIVE_APP_API + "/user/favorite",
  HISTORY_ORDER_LIST_API: REACT_NATIVE_APP_API + "/user/history/{search_orderid}",
  HISTORY_ORDER_LIST_SEARCH_API: REACT_NATIVE_APP_API + "/user/history/",
  HISTORY_ORDER_DETAIL_LIST_API: REACT_NATIVE_APP_API + "/user/history_detail/",

  //API_PRODUCT
  BEST_SELLING_PRODUCT_LISTVIEW_API : REACT_NATIVE_APP_API + "/products/best_selling",
  POPULARITY_PRODUCT_LISTVIEW_API : REACT_NATIVE_APP_API + "/products/popularity",
  CATEGORY_PRODUCT_LISTVIEW_API : REACT_NATIVE_APP_API + "/products/category",
  CATEGORY_PRODUCT_SEARCH_API : REACT_NATIVE_APP_API + "/products/category/",
  PRODUCT_SEARCH_HD_API : REACT_NATIVE_APP_API + "/products/",

  // CART_API
  ADD_CART_ORDER_LISTVIEW_API: REACT_NATIVE_APP_API + "/cart",
  COUNT_CART_ORDER_LISTVIEW_API: REACT_NATIVE_APP_API + "/cart/count",
  SAVE_CART_ORDER_LISTVIEW_API: REACT_NATIVE_APP_API + "/cart/save",

  //SOCAIL_API
  SOCIALS_LIST_HD_API: REACT_NATIVE_APP_API + "/socials",

  //PAYMENT_API
  BANK_LIST_HD_API: REACT_NATIVE_APP_API + "/bank/",
  CHECK_ORDER_PAYMENT_API: REACT_NATIVE_APP_API + "/payments/check/",
  PAYMENTS_TRANSFER_API: REACT_NATIVE_APP_API + "/payments",

};
